apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
  namespace: container-image-builder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2018-02-09T22-40-05Z
          args:
            - server
            - /date
          ports:
            - containerPort: 9000
              name: minio
          env:
            - name: MINIO_ACCESS_KEY
              value: 8Q9U4RBHKKB6HU70SRZ1
            - name: MINIO_SECRET_KEY
              value: oxxT2iqBlW6lgaDVe8ll6mP8z/OSVIUnn9cB4+Q0
          resources:
            requests:
              memory: "100M"
              cpu: "300m"
            limits:
              memory: "100M"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /minio/login
              port: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: container-image-builder
spec:
  ports:
    - port: 9000
  selector:
    app: minio